databases:
  - name: appointments
    databaseName: appointments_d96n
    user: appointments_d96n_user

services:
  - type: web
    name: BookItNow
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appointments
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
